# Generated by Django 2.2.17 on 2021-03-10 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import intempo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('artist', models.CharField(max_length=30)),
                ('creation_date', models.DateField()),
                ('album_cover', models.ImageField(blank=True, upload_to='album_covers')),
                ('description', models.TextField()),
                ('tags', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('join_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_posted', models.DateField()),
                ('review_text', models.TextField()),
                ('rating', models.FloatField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intempo.Album')),
                ('user', models.ForeignKey(on_delete=models.SET(intempo.models.get_sentinel_user), to='intempo.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_posted', models.DateField()),
                ('comment_text', models.TextField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intempo.Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intempo.UserProfile')),
            ],
        ),
    ]
