# Generated by Django 2.2.17 on 2021-03-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intempo', '0003_remove_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='deleted_user', max_length=20),
        ),
    ]
