# Generated by Django 2.2.17 on 2021-03-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intempo', '0006_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
